// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NsmUIClient is the client API for NsmUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NsmUIClient interface {
	// ListSidecarSpecs returns a list of Service Sidecar(s) that can be started through the UI.
	ListSidecarSpecs(ctx context.Context, in *ListSidecarSpecsRequest, opts ...grpc.CallOption) (NsmUI_ListSidecarSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type nsmUIClient struct {
	cc grpc.ClientConnInterface
}

func NewNsmUIClient(cc grpc.ClientConnInterface) NsmUIClient {
	return &nsmUIClient{cc}
}

func (c *nsmUIClient) ListSidecarSpecs(ctx context.Context, in *ListSidecarSpecsRequest, opts ...grpc.CallOption) (NsmUI_ListSidecarSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &NsmUI_ServiceDesc.Streams[0], "/v1.NsmUI/ListSidecarSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &nsmUIListSidecarSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NsmUI_ListSidecarSpecsClient interface {
	Recv() (*ListSidecarSpecsResponse, error)
	grpc.ClientStream
}

type nsmUIListSidecarSpecsClient struct {
	grpc.ClientStream
}

func (x *nsmUIListSidecarSpecsClient) Recv() (*ListSidecarSpecsResponse, error) {
	m := new(ListSidecarSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nsmUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.NsmUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NsmUIServer is the server API for NsmUI service.
// All implementations must embed UnimplementedNsmUIServer
// for forward compatibility
type NsmUIServer interface {
	// ListSidecarSpecs returns a list of Service Sidecar(s) that can be started through the UI.
	ListSidecarSpecs(*ListSidecarSpecsRequest, NsmUI_ListSidecarSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedNsmUIServer()
}

// UnimplementedNsmUIServer must be embedded to have forward compatible implementations.
type UnimplementedNsmUIServer struct {
}

func (UnimplementedNsmUIServer) ListSidecarSpecs(*ListSidecarSpecsRequest, NsmUI_ListSidecarSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListSidecarSpecs not implemented")
}
func (UnimplementedNsmUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedNsmUIServer) mustEmbedUnimplementedNsmUIServer() {}

// UnsafeNsmUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NsmUIServer will
// result in compilation errors.
type UnsafeNsmUIServer interface {
	mustEmbedUnimplementedNsmUIServer()
}

func RegisterNsmUIServer(s grpc.ServiceRegistrar, srv NsmUIServer) {
	s.RegisterService(&NsmUI_ServiceDesc, srv)
}

func _NsmUI_ListSidecarSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListSidecarSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NsmUIServer).ListSidecarSpecs(m, &nsmUIListSidecarSpecsServer{stream})
}

type NsmUI_ListSidecarSpecsServer interface {
	Send(*ListSidecarSpecsResponse) error
	grpc.ServerStream
}

type nsmUIListSidecarSpecsServer struct {
	grpc.ServerStream
}

func (x *nsmUIListSidecarSpecsServer) Send(m *ListSidecarSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _NsmUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsmUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.NsmUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsmUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NsmUI_ServiceDesc is the grpc.ServiceDesc for NsmUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NsmUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.NsmUI",
	HandlerType: (*NsmUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _NsmUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListSidecarSpecs",
			Handler:       _NsmUI_ListSidecarSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nsm-ui.proto",
}
