// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NsmServiceClient is the client API for NsmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NsmServiceClient interface {
	// StartLocalSidecar starts a Service Sidecar on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the nsm/config.yaml
	//   3. all bytes constituting the Sidecar YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalSidecar(ctx context.Context, opts ...grpc.CallOption) (NsmService_StartLocalSidecarClient, error)
	// StartFromPreviousSidecar starts a new Sidecar based on a previous one.
	// If the previous Sidecar does not have the can-replay condition set this call will result in an error.
	StartFromPreviousSidecar(ctx context.Context, in *StartFromPreviousSidecarRequest, opts ...grpc.CallOption) (*StartSidecarResponse, error)
	// StartSidecarRequest starts a new Sidecar based on its specification.
	StartSidecar(ctx context.Context, in *StartSidecarRequest, opts ...grpc.CallOption) (*StartSidecarResponse, error)
	// Searches for Sidecar(s) known to this Sidecar
	ListSidecars(ctx context.Context, in *ListSidecarsRequest, opts ...grpc.CallOption) (*ListSidecarsResponse, error)
	// Subscribe listens to new Sidecar(s) updates
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (NsmService_SubscribeClient, error)
	// GetSidecar retrieves details of a single Sidecar
	GetSidecar(ctx context.Context, in *GetSidecarRequest, opts ...grpc.CallOption) (*GetSidecarResponse, error)
	// Listen listens to Sidecar updates and log output of a running Sidecar
	Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (NsmService_ListenClient, error)
	// StopSidecar stops a currently running Sidecar
	StopSidecar(ctx context.Context, in *StopSidecarRequest, opts ...grpc.CallOption) (*StopSidecarResponse, error)
}

type nsmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNsmServiceClient(cc grpc.ClientConnInterface) NsmServiceClient {
	return &nsmServiceClient{cc}
}

func (c *nsmServiceClient) StartLocalSidecar(ctx context.Context, opts ...grpc.CallOption) (NsmService_StartLocalSidecarClient, error) {
	stream, err := c.cc.NewStream(ctx, &NsmService_ServiceDesc.Streams[0], "/v1.NsmService/StartLocalSidecar", opts...)
	if err != nil {
		return nil, err
	}
	x := &nsmServiceStartLocalSidecarClient{stream}
	return x, nil
}

type NsmService_StartLocalSidecarClient interface {
	Send(*StartLocalSidecarRequest) error
	CloseAndRecv() (*StartSidecarResponse, error)
	grpc.ClientStream
}

type nsmServiceStartLocalSidecarClient struct {
	grpc.ClientStream
}

func (x *nsmServiceStartLocalSidecarClient) Send(m *StartLocalSidecarRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nsmServiceStartLocalSidecarClient) CloseAndRecv() (*StartSidecarResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StartSidecarResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nsmServiceClient) StartFromPreviousSidecar(ctx context.Context, in *StartFromPreviousSidecarRequest, opts ...grpc.CallOption) (*StartSidecarResponse, error) {
	out := new(StartSidecarResponse)
	err := c.cc.Invoke(ctx, "/v1.NsmService/StartFromPreviousSidecar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsmServiceClient) StartSidecar(ctx context.Context, in *StartSidecarRequest, opts ...grpc.CallOption) (*StartSidecarResponse, error) {
	out := new(StartSidecarResponse)
	err := c.cc.Invoke(ctx, "/v1.NsmService/StartSidecar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsmServiceClient) ListSidecars(ctx context.Context, in *ListSidecarsRequest, opts ...grpc.CallOption) (*ListSidecarsResponse, error) {
	out := new(ListSidecarsResponse)
	err := c.cc.Invoke(ctx, "/v1.NsmService/ListSidecars", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsmServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (NsmService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &NsmService_ServiceDesc.Streams[1], "/v1.NsmService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &nsmServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NsmService_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type nsmServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *nsmServiceSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nsmServiceClient) GetSidecar(ctx context.Context, in *GetSidecarRequest, opts ...grpc.CallOption) (*GetSidecarResponse, error) {
	out := new(GetSidecarResponse)
	err := c.cc.Invoke(ctx, "/v1.NsmService/GetSidecar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsmServiceClient) Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (NsmService_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &NsmService_ServiceDesc.Streams[2], "/v1.NsmService/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &nsmServiceListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NsmService_ListenClient interface {
	Recv() (*ListenResponse, error)
	grpc.ClientStream
}

type nsmServiceListenClient struct {
	grpc.ClientStream
}

func (x *nsmServiceListenClient) Recv() (*ListenResponse, error) {
	m := new(ListenResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nsmServiceClient) StopSidecar(ctx context.Context, in *StopSidecarRequest, opts ...grpc.CallOption) (*StopSidecarResponse, error) {
	out := new(StopSidecarResponse)
	err := c.cc.Invoke(ctx, "/v1.NsmService/StopSidecar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NsmServiceServer is the server API for NsmService service.
// All implementations must embed UnimplementedNsmServiceServer
// for forward compatibility
type NsmServiceServer interface {
	// StartLocalSidecar starts a Service Sidecar on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the nsm/config.yaml
	//   3. all bytes constituting the Sidecar YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalSidecar(NsmService_StartLocalSidecarServer) error
	// StartFromPreviousSidecar starts a new Sidecar based on a previous one.
	// If the previous Sidecar does not have the can-replay condition set this call will result in an error.
	StartFromPreviousSidecar(context.Context, *StartFromPreviousSidecarRequest) (*StartSidecarResponse, error)
	// StartSidecarRequest starts a new Sidecar based on its specification.
	StartSidecar(context.Context, *StartSidecarRequest) (*StartSidecarResponse, error)
	// Searches for Sidecar(s) known to this Sidecar
	ListSidecars(context.Context, *ListSidecarsRequest) (*ListSidecarsResponse, error)
	// Subscribe listens to new Sidecar(s) updates
	Subscribe(*SubscribeRequest, NsmService_SubscribeServer) error
	// GetSidecar retrieves details of a single Sidecar
	GetSidecar(context.Context, *GetSidecarRequest) (*GetSidecarResponse, error)
	// Listen listens to Sidecar updates and log output of a running Sidecar
	Listen(*ListenRequest, NsmService_ListenServer) error
	// StopSidecar stops a currently running Sidecar
	StopSidecar(context.Context, *StopSidecarRequest) (*StopSidecarResponse, error)
	mustEmbedUnimplementedNsmServiceServer()
}

// UnimplementedNsmServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNsmServiceServer struct {
}

func (UnimplementedNsmServiceServer) StartLocalSidecar(NsmService_StartLocalSidecarServer) error {
	return status.Errorf(codes.Unimplemented, "method StartLocalSidecar not implemented")
}
func (UnimplementedNsmServiceServer) StartFromPreviousSidecar(context.Context, *StartFromPreviousSidecarRequest) (*StartSidecarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartFromPreviousSidecar not implemented")
}
func (UnimplementedNsmServiceServer) StartSidecar(context.Context, *StartSidecarRequest) (*StartSidecarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSidecar not implemented")
}
func (UnimplementedNsmServiceServer) ListSidecars(context.Context, *ListSidecarsRequest) (*ListSidecarsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSidecars not implemented")
}
func (UnimplementedNsmServiceServer) Subscribe(*SubscribeRequest, NsmService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedNsmServiceServer) GetSidecar(context.Context, *GetSidecarRequest) (*GetSidecarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSidecar not implemented")
}
func (UnimplementedNsmServiceServer) Listen(*ListenRequest, NsmService_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (UnimplementedNsmServiceServer) StopSidecar(context.Context, *StopSidecarRequest) (*StopSidecarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSidecar not implemented")
}
func (UnimplementedNsmServiceServer) mustEmbedUnimplementedNsmServiceServer() {}

// UnsafeNsmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NsmServiceServer will
// result in compilation errors.
type UnsafeNsmServiceServer interface {
	mustEmbedUnimplementedNsmServiceServer()
}

func RegisterNsmServiceServer(s grpc.ServiceRegistrar, srv NsmServiceServer) {
	s.RegisterService(&NsmService_ServiceDesc, srv)
}

func _NsmService_StartLocalSidecar_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NsmServiceServer).StartLocalSidecar(&nsmServiceStartLocalSidecarServer{stream})
}

type NsmService_StartLocalSidecarServer interface {
	SendAndClose(*StartSidecarResponse) error
	Recv() (*StartLocalSidecarRequest, error)
	grpc.ServerStream
}

type nsmServiceStartLocalSidecarServer struct {
	grpc.ServerStream
}

func (x *nsmServiceStartLocalSidecarServer) SendAndClose(m *StartSidecarResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nsmServiceStartLocalSidecarServer) Recv() (*StartLocalSidecarRequest, error) {
	m := new(StartLocalSidecarRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _NsmService_StartFromPreviousSidecar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartFromPreviousSidecarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsmServiceServer).StartFromPreviousSidecar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.NsmService/StartFromPreviousSidecar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsmServiceServer).StartFromPreviousSidecar(ctx, req.(*StartFromPreviousSidecarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsmService_StartSidecar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSidecarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsmServiceServer).StartSidecar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.NsmService/StartSidecar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsmServiceServer).StartSidecar(ctx, req.(*StartSidecarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsmService_ListSidecars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSidecarsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsmServiceServer).ListSidecars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.NsmService/ListSidecars",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsmServiceServer).ListSidecars(ctx, req.(*ListSidecarsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsmService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NsmServiceServer).Subscribe(m, &nsmServiceSubscribeServer{stream})
}

type NsmService_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type nsmServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *nsmServiceSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _NsmService_GetSidecar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSidecarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsmServiceServer).GetSidecar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.NsmService/GetSidecar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsmServiceServer).GetSidecar(ctx, req.(*GetSidecarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsmService_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NsmServiceServer).Listen(m, &nsmServiceListenServer{stream})
}

type NsmService_ListenServer interface {
	Send(*ListenResponse) error
	grpc.ServerStream
}

type nsmServiceListenServer struct {
	grpc.ServerStream
}

func (x *nsmServiceListenServer) Send(m *ListenResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _NsmService_StopSidecar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSidecarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsmServiceServer).StopSidecar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.NsmService/StopSidecar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsmServiceServer).StopSidecar(ctx, req.(*StopSidecarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NsmService_ServiceDesc is the grpc.ServiceDesc for NsmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NsmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.NsmService",
	HandlerType: (*NsmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartFromPreviousSidecar",
			Handler:    _NsmService_StartFromPreviousSidecar_Handler,
		},
		{
			MethodName: "StartSidecar",
			Handler:    _NsmService_StartSidecar_Handler,
		},
		{
			MethodName: "ListSidecars",
			Handler:    _NsmService_ListSidecars_Handler,
		},
		{
			MethodName: "GetSidecar",
			Handler:    _NsmService_GetSidecar_Handler,
		},
		{
			MethodName: "StopSidecar",
			Handler:    _NsmService_StopSidecar_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartLocalSidecar",
			Handler:       _NsmService_StartLocalSidecar_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _NsmService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Listen",
			Handler:       _NsmService_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nsm.proto",
}
